Vagrant.configure("2") do |config|

  BOX = "ubuntu/bionic64"

  WEB_IP = "192.168.56.10"
  DB_IP  = "192.168.56.11"

  config.vm.define "web" do |web|

    web.vm.box = BOX

    web.vm.hostname = "web"

    web.vm.network "private_network",
      ip: WEB_IP

    web.vm.provision "shell",
      path: "scripts/web.sh"

  end

  config.vm.define "db" do |db|

    db.vm.box = BOX

    db.vm.hostname = "db"

    db.vm.network "private_network",
      ip: DB_IP

    db.vm.provision "shell",
      path: "scripts/db.sh"

  end

end
